apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'), 
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditarNoticia, name='edit_noticia'),
    path('detalle/ajax/cargar_comentarios/<int:noticia_id>/', views.cargar_comentarios, name='cargar_comentarios'),
    path('detalle/ajax/eliminar_comentarios/<int:id_comentario>/', views.eliminar_comentarios, name='eliminar_comentarios'),
    #path('ajax/<int:pk>', views.cargar_comentarios, name='ejemploajax'),
    #path('panel_noticias', views.PanelNoticias, name='panel_noticias'),
]

apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registro/', views.Registro.as_view(), name='registro'),
    path('perfil/<int:pk>/edit/', views.Perfil, name='perfil'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls'),name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('acercade/', include('apps.acercade.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
    #parametro 3: el nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from apps.usuarios.models import Usuario
from django.db.models.signals import post_save
from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.models import LogEntry, CHANGE
from model_utils import FieldTracker
from apps.noticias.middleware import get_current_user

# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Noticia(models.Model):
    # = VARCHAR | max_length longitud max
    titulo = models.CharField(max_length=255)
    # Uso de ckeditor para usar el edito html
    contenido = RichTextField()
    resumen = models.CharField(max_length=200, null=True)
    # imagen requiere la libreria pillow
    imagenes = models.ImageField(upload_to='noticias')
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    categoria_noticia = models.ForeignKey(
        Categoria, on_delete=models.SET_NULL, null=True)

    cant_vistas = models.IntegerField(default=0)
    # Para poder default=Usuario.objects.get(is_superuser=True).pk tiene que existir el super usuario
    autor = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)
    # Usamos FieldTracker para realizar un seguimiento de los cambios en los campos

    tracker = FieldTracker()

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    noticia = models.ForeignKey(
        Noticia, on_delete=models.CASCADE, related_name='comentarios',)
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.contenido


# Definir una función para manejar la lógica de detección de cambios y guardar en LogEntry
@receiver(post_save, sender=Noticia)
def detectar_y_guardar_cambios(sender, instance, created, **kwargs):
    # Verificar si se está creando un nuevo objeto (en lugar de actualizar)
    guardar = False
    if created:
        change_message= "Se crea Articulo"
        guardar = True

    else:
        changes = []
        # Crear una nueva entrada de historial solo si hay cambios
        change_message = "Modificación de: "
        

        if instance.tracker.has_changed('titulo'):
            changes.append("titulo")
            guardar = True
        if instance.tracker.has_changed('contenido'):
            changes.append("contenido")
            guardar = True

        if instance.tracker.has_changed('resumen'):
            changes.append("resumen")
            guardar = True

        if instance.tracker.has_changed('imagenes'):
            changes.append("imagenes")
            guardar = True

        if instance.tracker.has_changed('categoria_noticia_id'):
            changes.append("categoria noticia")
            guardar = True

        # Concatenar los cambios acumulados
        change_message += ", ".join(changes)

        
    if guardar:
        user = get_current_user()
        content_type = ContentType.objects.get_for_model(instance)
        LogEntry.objects.create(
            content_type=content_type,
            object_id=instance.pk,
            object_repr=str(instance),
            action_flag=CHANGE,
            user_id=user.pk,
            change_message=change_message,
        )


# Registrar la función para escuchar la señal post_save
post_save.connect(detectar_y_guardar_cambios, sender=Noticia)

apps/noticias/forms.py
from django import forms
from .models import Noticia
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, HTML
from django.forms import ImageField, FileInput

class NoticiaForm(forms.ModelForm):
    imagenes = ImageField(widget=FileInput,label="Nueva Imagen")
    class Meta:
        model = Noticia
        fields = [
            'titulo',
            'resumen',
            'contenido',
            'imagenes',
            'categoria_noticia',
        ]
        widgets = {
            'titulo': forms.TextInput(),
            'resumen': forms.Textarea(),
            'categoria_noticia': forms.Select(attrs={'class': 'form-control'}),
            'imagenes': forms.ClearableFileInput(attrs={'class': 'form-control', 'label': 'Nueva Etiqueta'}),
        }


    def __init__(self, *args, **kwargs):
        super(NoticiaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-group'
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            'titulo',
            'resumen',
            'categoria_noticia',
            HTML("""
                {% if form.instance.imagenes %}
                <label for="id_resumen" class=" requiredField">
                Imagen asociada<span class="asteriskField">*</span> </label>
                    <div>
                        <img style="max-width: 500px;" class=" rounded mx-auto d-block img-thumbnail" src="{{ form.instance.imagenes.url }}">
                         
                    </div>
                    <br/>
                {% endif %}
                  
              
            """),
            'imagenes',
            'contenido',
        )

apps/noticias/views.py
import threading
from django.shortcuts import get_object_or_404, render, redirect

from apps.noticias.forms import NoticiaForm
from .models import Noticia, Categoria, Comentario
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.db.models.functions import TruncYear, TruncMonth
from django.urls import reverse
from datetime import datetime
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django_ajax.decorators import ajax
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string

from django.contrib.admin.models import LogEntry
from django.contrib.contenttypes.models import ContentType


# Create your views here.
# Creamos un objeto local enhebrado para almacenar el usuario actual
thread_local = threading.local()


def get_current_user():
    return getattr(thread_local, 'user', None)

# Definir una función middleware para establecer el usuario actual en cada solicitud


class CurrentUserMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        thread_local.user = request.user
        response = self.get_response(request)
        return response


def ListarNoticias(request):
    contexto = {}
    categoria_todos = Categoria(pk=0, nombre='Todas')
    id_categoria = request.GET.get("id", "0")
    antiguedad = request.GET.get("antiguedad", None)
    buscar = request.GET.get("buscar", None)
    orden = request.GET.get("orden", None)
    archivo = request.GET.get("archivo", None)
    page = request.GET.get('page', 1)
    fecha_objeto = None

    n = Noticia.objects.all()

    if id_categoria != "0":
        n = n.filter(categoria_noticia=id_categoria)
        cat = Categoria.objects.get(id=id_categoria)
    else:
        cat = categoria_todos

    if buscar:
        n = n.filter(Q(titulo__icontains=buscar) |
                     Q(contenido__icontains=buscar))

    if archivo:

        try:
            fecha_objeto = datetime.strptime(archivo, '%m-%Y').date()

        except ValueError:
            fecha_objeto = None

        if fecha_objeto:
            n = n.filter(fecha_publicacion__month=fecha_objeto.month,
                         fecha_publicacion__year=fecha_objeto.year)

    if antiguedad:
        if antiguedad == "asc":
            n = n.order_by('fecha_publicacion')
        elif antiguedad == "desc":
            n = n.order_by('-fecha_publicacion')
    else:
        n = n.order_by('-fecha_publicacion')

    if orden:
        if orden == "asc":
            n = n.order_by('titulo')
        elif orden == "desc":
            n = n.order_by('-titulo')

    # Crear un objeto Paginator
    registros_por_pagina = 5
    paginator = Paginator(n, registros_por_pagina)
    # Obtener el número de página desde la solicitud GET

    try:
        # Obtener la página actual
        registros_pagina_actual = paginator.page(page)
    except PageNotAnInteger:
        # Si la página no es un número entero, mostrar la primera página
        registros_pagina_actual = paginator.page(1)
    except EmptyPage:
        # Si la página está fuera de rango, mostrar la última página
        registros_pagina_actual = paginator.page(paginator.num_pages)

    # Obtener la cantidad total de registros
    total_registros = paginator.count

    # Calcular la cantidad total de páginas
    total_paginas = paginator.num_pages

    contexto = {
        'noticias': n,
        'registros': registros_pagina_actual,
        'total_registros': total_registros,
        'total_paginas': total_paginas,
        'categoria_select': cat,
        'orden': orden,
        'antiguedad': antiguedad,
        'page': page,
        'buscar': buscar,
        'archivo': archivo,
        'fecha_objeto': fecha_objeto

    }
    contexto = PanelNoticias(contexto)

    return render(request, 'noticias/listar.html', contexto)


def DetalleNoticia(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk=pk)  # SELECT * FROM NOTICIAS WHERE id = 1
    c = n.comentarios.all()
    # actualizar numeros de visitas
    n.cant_vistas = n.cant_vistas + 1
    n.save()

    contexto = {
        'noticias': n,
        'comentarios': c,
    }

    contexto = PanelNoticias(contexto)

    id_categoria = request.GET.get("id", None)
    archivo = request.GET.get("archivo", None)
    redirect_url = reverse('noticias:listar')

    if id_categoria is not None:
        redirect_url += f'?id={id_categoria}'
        return redirect(redirect_url)
    elif archivo is not None:
        redirect_url += f'?archivo={archivo}'
        return redirect(redirect_url)
    else:
        return render(request, 'noticias/detalle.html', contexto)


def Ultmias10Noticias(request):
    contexto = {}
    n = Noticia.objects. all().order_by('-fecha_publicacion')[:10]


def PanelNoticias(contexto):
    categoria_todos = Categoria(pk=0, nombre='Todas')
    # Categorias disponibles

    cat = []
    cat.append(categoria_todos)
    # ordena por nombre
    cat.extend(list(Categoria.objects.all().order_by('nombre')))

    contexto['categorias'] = cat

    # Top Noticias
    n = Noticia.objects. all().order_by('-cant_vistas')[:3]
    contexto['popular_noticias'] = n

    resumen_noticias = (
        Noticia.objects
        .annotate(month=TruncMonth('fecha_publicacion'))
        .values('month')
        .annotate(cant_noticias=Count('id'))
    )

    # Formatear y mostrar el resumen
    contexto['resumen_noticias'] = resumen_noticias

    return contexto


@ajax
@login_required
def cargar_comentarios(request, noticia_id):
    noticia = get_object_or_404(Noticia, id=noticia_id)
    contexto = {}
    if request.method == 'POST':
        # Obtener el contenido del comentario desde la solicitud POST
        comentario_contenido = request.POST.get('contenido', '')
        id_comentario = request.POST.get('id_comentario', '')
        id_comentario = int(id_comentario) if id_comentario.strip() else 0
        usuario = request.user

        # Verificar si el comentario no está vacío
        if not comentario_contenido:
            return JsonResponse({'error': 'El comentario no puede estar vacío'}, status=400)

        # Lógica para crear un comentario en la base de datos
        if id_comentario == 0:
            Comentario.objects.create(
                noticia=noticia, usuario=usuario, contenido=comentario_contenido)
        else:
            comentario = get_object_or_404(Comentario, id=id_comentario)
            comentario.contenido = comentario_contenido
            comentario.save()

        c = noticia.comentarios.all()
        contexto = {
            'comentarios': c,
            'user': usuario
        }

        comentario_html = render_to_string(
            'noticias/comentarios.html', contexto)

        return HttpResponse(comentario_html)
    return JsonResponse({'error': 'Solicitud no válida'}, status=400)


@ajax
@login_required
def eliminar_comentarios(request, id_comentario):
    comentario = get_object_or_404(Comentario, id=id_comentario)
    contexto = {}
    if request.method == 'GET':
        # Obtener el contenido del comentario desde la solicitud POST

        usuario = request.user
        id = comentario.noticia.pk
        if comentario.usuario == request.user or usuario.is_staff:
            comentario.delete()

        noticia = get_object_or_404(Noticia, id=id)
        c = noticia.comentarios.all()
        contexto = {
            'comentarios': c,
            'user': usuario
        }

        comentario_html = render_to_string(
            'noticias/comentarios.html', contexto)

        return HttpResponse(comentario_html)
    return JsonResponse({'error': 'Solicitud no válida'}, status=400)


@login_required
def AddNoticia(request):
    if request.user.is_staff == False:
        return redirect('home:inicio')
    if request.method == 'POST':
        # Request files es para las imagenes
        form = NoticiaForm(request.POST or None, request.FILES)

        if form.is_valid():
            noticia = form.save(commit=False)
            noticia.autor = request.user
            form.save()
            redirect_url = reverse('noticias:listar')
            return redirect(redirect_url)
    else:
        form = NoticiaForm()

    return render(request, 'noticias/addNoticia.html', {'form': form})


@login_required
def EditarNoticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    content_type = ContentType.objects.get_for_model(noticia)
    # Obtener las entradas de historial de cambios para tu modelo
    history_entries = LogEntry.objects.filter(
        content_type=content_type, object_id=pk).order_by('-action_time')[:10]

    # Solo el autor puede editar la noticia
    if noticia.autor != request.user:
       return redirect('home:inicio')

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    context = {
        'form': form,
        'history': history_entries,
        'user': request.user
    }
    return render(request, 'noticias/editar.html', context)

templates/noticias/addNoticia.html
{% extends 'base.html' %} {% load static %} 
{% block contenido %} 
{% include "navbar.html" %}
{% load crispy_forms_tags %}
<div id="page_content">
  <section
    id="bg-blog-detail-img"
     
    class="bg-blog-detail-img"
  >
    <div class="overlay"></div>
  </section>
  <section id="search">
    <div class="container">
      <div class="row pt-lg-5">
        <div class="col-sm-12 col-ms-12 col-lg-12">
          <h2>Nueva Noticia</h2>
          <hr />
          <form
            action=""
            class="post-form"
            method="post"
            enctype="multipart/form-data"
          >
            {% csrf_token %} 
            {{ form.media }}
            {% crispy form %}
            <button class="btn btn-success boton-flotante" type="submit">Crear Nuevo  <i class="las la-save"></i></button>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor-init.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"
></script>

 
{% endblock contenido %}

templates/noticias/cargar_comentarios.html
{% for comment in noticias.comentarios.all %}

<div class="comment">
  <div class="comment_write">
    <div class="icon_comment">
      <i class="far fa-user user_icon"></i>

      <div class="icon_text">
        <h1 class="main_written font">{{comment.usuario}}</h1>
        <p class="date margin_days text-black">{{comment.fecha_creacion}}</p>
      </div>
    </div>
    <p class="sub-heading mt-1">{{comment.contenido}}</p>
  </div>
</div>
{% endfor %}

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
{% include "navbar.html" %}
<div id="page_content" idNoticia="{{noticias.id}}">
  <!--HEADER IMAGE-->
  <section
    id="bg-blog-detail-img"
    style="background-image: url({{noticias.imagenes.url}});"
    class="bg-blog-detail-img"
  >
    <div class="overlay"></div>
  </section>

  <section id="search">
    <div class="container">
      <div class="row pt-lg-5">
        <div class="col-sm-12 col-ms-8 col-lg-8">
          <div class="text_minimal pt-0">
            <h1 class="pt-3 font-weight-bold blog_detail-heading text-black">
              {{noticias.titulo}}
            </h1>
            <div class="portfolio-text">
              <p class="portfolio-vert text-grey">{{noticias.fecha_publicacion}} | {{noticias.categoria_noticia}} | <i class="las la-eye"></i> {{noticias.cant_vistas}} visitas</p>
              
              <div class="horizontal-line"></div>
              
          </p></div>
            <p class="sub-heading pt-0 text-grey">
              {{noticias.contenido|safe}}
            </p>
          </div>

          <div class="horizontal-line mt-5"></div>

          <div class="written">
            <div class="written_outerbox mt-5 display">
              <img
                class="written_img circle-image"
                src="{{noticias.autor.imagenes.url}}"
                alt=""
              />
              <div class="written_text">
                <p class="date text-black">ESCRITO POR</p>
                <h1 class="main_written text-black">{{noticias.autor}}</h1>
              </div>
            </div>
          </div>
          <div id="test">{% include "./comentarios.html" %}</div>
          {% if user.is_authenticated %}
          <h1 class="comment_text text-black mt-6 mb-5">
            ESCRIBIR UN COMENTARIO
          </h1>

          {% include "./formcomentario.html" %} {% else %}
          <h4 class="comment_text text-black mt-6 mb-5">
 
            <a class="comment_text text-black mt-6 mb-5" style="font-size: 25px;color: cornflowerblue;" href="{% url 'usuarios:login' %}">Iniciar sesion para escribir un comentario</a>
          </h4>
          {% endif %}
        </div>
        {% include "./panel_noticias.html" %}
      </div>
    </div>
  </section>
  {% if   user.is_staff %}
  <a href="{% url 'noticias:edit_noticia' pk=noticias.pk %}" class="btn btn-info boton-flotante">
    Editar artículo

    <i class="las la-pen"></i>
  </a>
  {% endif %}
 

<!-- Modal de confirmación -->
<div
  class="modal fade"
  id="confirmModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="confirmModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmModalLabel">
          Confirmar Eliminación
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Estás seguro de que deseas eliminar este comentario?
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btncomment btn-secondary"
          data-dismiss="modal"
        >
          Cancelar
        </button>
        <button
          type="button"
          class="btn btncomment btn-danger"
          id="confirmDeleteBtn"
        >
          Eliminar
        </button>
        <div
          id="loading-comment"
          class="spinner-border text-info d-none"
          role="status"
        ></div>
      </div>
    </div>
  </div>
</div>
 
{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %} 
{% load static %} 
{% block contenido %} 
{% include "navbar.html" %}

<div id="page_content">
  
  {% if user.is_staff %}
  <a href="{% url 'noticias:addnoticia' %}" class="btn btn-success boton-flotante">
    Nuevo artículo

    <i class="las la-plus"></i>
  </a>
  {% endif %}
    
  <section id="bg-top-stories-img" class="bg-top-stories-img">
    <div class="overlay"></div>
    <div class="container">
      <div class="row" style="height: 350px">
        <div class="col-12 align-items-center container" style="top: 40%">
           
        </div>
      </div>
    </div>
  </section>

  <section id="search">
    <div class="container">
      <div class="row pt-sm-5">
        {% include "./panel_noticias.html" %}

        <div
          class="col-sm-12 col-md-12 col-lg-8 pt-sm-4 pt-md-0 pt-lg-0   order-md-2" >
          <ul class="nav justify-content-end">
           
            <li class="nav-item">
              
              <div class="btn-group" role="group" aria-label="Basic example">
                <a type="button" style="text-decoration: auto;" class="btn {% if orden %}btn-dark{% else %}btn-outline-dark{% endif %}" href="?orden={% if orden  == 'asc' %}desc{% else %}asc{% endif %}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}"  >
                  Orden
                  {% if orden is None %}
                      <i class="las la-sort-alpha-down"></i>
                  {% elif orden  == 'asc' %}
                      <i class="las la-sort-alpha-down"></i>
                  
                  {% else %}
                      <i class="las la-sort-alpha-up-alt"></i>
                  {% endif %}
                </a>
                <a type="button" style="text-decoration: auto;" class="btn {% if antiguedad %}btn-dark{% else %}btn-outline-dark{% endif %}"   href="?antiguedad={% if antiguedad  == 'asc' %}desc{% else %}asc{% endif %}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}"  >Fecha  
                  {% if antiguedad is None %}
                     <i class="las la-sort-amount-up"></i>
                  {% elif antiguedad  == 'asc'  %}
                     <i class="las la-sort-amount-down-alt"></i>
                  {% else %}
                     <i class="las la-sort-amount-up"></i>
                  {% endif %}
            
                  
                </a>

              </div>
              
            </li>
          </ul>
           
          {%if fecha_objeto %}
            <h4> {{ fecha_objeto|date:'F Y'|capfirst }}<a href="?{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}" class="badge badge"><i class="las la-times"></i></a></h4>
            
          {%endif%}
          <!--..................MINIMAL POST....-->
          {% for noticia in registros %}
          <div class="minimal_image   mt-10">
            <section class="min-post">
              <img src="{{noticia.imagenes.url}}" alt="Blog Image" />
            </section>
          </div>
          <div class="text_minimal">
            <a
              class="text-black"
              href="{% url 'noticias:detalle' noticia.pk %}"
            >
              <h2>{{noticia.titulo}}</h2>
              
            </a>
            <div class="display">
              <p class="date text-black">{{noticia.fecha_publicacion}}</p>
              <div class="verticle_line margin_1 bg-black"></div>
              <span>{{noticia.autor}}</span>
              <div class="verticle_line margin_1 bg-black"></div>
              <span>{{noticia.categoria_noticia}}</span>
              <div class="verticle_line margin_1 bg-black"></div>
              <span><i class="las la-eye"></i> {{noticia.cant_vistas}} visitas</span>
            </div>
            <p class="sub-heading text-grey">
                {{noticia.resumen}}
                ...</p>
            <a
              href="{% url 'noticias:detalle' noticia.pk %}"
              class="btn btn-large btn-primary"
              >Leer Más</a
            >
          </div>
          <div class="divider1"></div>
          {% endfor %}
          
          
          
          <!--..........PAGINATION..........-->
          <ul class="pagination mt-10">
            {% if registros.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}">&laquo; Primero</a>
            </li>
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ registros.previous_page_number }}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}"
                ><i class="fas fa-arrow-left"></i></a
              >
            </li>
            {% endif %} 
            {% for i in registros.paginator.page_range %}
                {% if registros.number == i %}
                    <li class="page-item active">
                        <span class="page-link" >{{ i }} 
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ i }}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}">{{ i }}</a>
                    </li>
                {% endif %} 
            {% endfor %}

            {% if registros.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ registros.next_page_number }}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}">

                    <i class="fas fa-arrow-right"></i></a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ registros.paginator.num_pages }}{% if categoria_select %}&id={{ categoria_select.pk }}{% endif %}{% if orden %}&orden={{ orden }}{% endif %}{% if antiguedad %}&antiguedad={{ antiguedad }}{% endif %}{% if buscar %}&buscar={{ buscar }}{% endif %}{% if archivo %}&archivo={{ archivo }}{% endif %}">&raquo; Último</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>

  
</div>
<script>
  resaltarTexto() 
</script>
{% endblock contenido %}