apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'), 
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditarNoticia, name='edit_noticia'),
    path('detalle/ajax/cargar_comentarios/<int:noticia_id>/', views.cargar_comentarios, name='cargar_comentarios'),
    path('detalle/ajax/eliminar_comentarios/<int:id_comentario>/', views.eliminar_comentarios, name='eliminar_comentarios'),
    #path('ajax/<int:pk>', views.cargar_comentarios, name='ejemploajax'),
    #path('panel_noticias', views.PanelNoticias, name='panel_noticias'),
]

apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registro/', views.Registro.as_view(), name='registro'),
    path('perfil/<int:pk>/edit/', views.Perfil, name='perfil'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls'),name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('acercade/', include('apps.acercade.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
    #parametro 3: el nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Usuario(AbstractUser):
    # Establecer la imagen por defecto
    imagenes = models.ImageField(upload_to='user', default='user/avatar.svg')

 # USUARIOS QUE TENEMOS EN NUESTRO BLOG Y SUS PERMISOS
    USUARIO_COLABORADOR = 'Colaborador'
    USUARIO_MIEMBRO = 'Miembro'
    USUARIO_SUPER = 'Superusuario'

    TIPOS_DE_USUARIO = [
        # is_superuser=False, is_staff=True
        (USUARIO_COLABORADOR, 'Colaborador'),
        (USUARIO_MIEMBRO, 'Miembro'),  # is_superuser=False, is_staff=False
        (USUARIO_SUPER, 'Superusuario'),  # is_superuser=True, is_staff=True
    ]
    # atributo que determina el tipo de usuario, por default es usuario_miembro (cuando te registras en el blog toma este)
    tipo_usuario = models.CharField(
        max_length=20, choices=TIPOS_DE_USUARIO, default=USUARIO_MIEMBRO)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


# Señal para asignar el tipo de usuario "Superusuario" cuando se crea un superusuario
@receiver(post_save, sender=Usuario)
def asignar_tipo_usuario(sender, instance, created, **kwargs):
    if created and instance.is_superuser:
        instance.tipo_usuario = Usuario.USUARIO_SUPER
        instance.save()
        print(f"Usuario {instance.username} es un Superusuario.")


# Señal para asignar el tipo de usuario "Miembro" cuando se crea un usuario
@receiver(post_save, sender=Usuario)
def asignar_miembro(sender, instance, created, **kwargs):
    if created and not instance.is_superuser:
        instance.tipo_usuario = Usuario.USUARIO_MIEMBRO
        instance.save()
        print(f"Usuario {instance.username} es un Miembro.")

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from .models import Usuario 
from django.forms import ImageField, FileInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, HTML


class RegistroForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Correo'}),
        label='',
        required=True
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Nombre'}),
        label='',
        required=True
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Apellido'}),
        label='',
        required=True
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Usuario'}),
        label='',
        required=True
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}),
        label='',
        required=True
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirmar Contraseña'}),
        label='',
        required=True
    )
    # imagen = forms.ImageField(label='Imagen de perfil', required=False)

    class Meta:
        model = Usuario
        fields = [
            'email',
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]
        


class PerfilForm(UserChangeForm):
    imagenes = ImageField(widget=FileInput, label="Nueva Imagen")
    

    # imagen = forms.ImageField(label='Imagen de perfil', required=False)

    class Meta:
        model = Usuario
        fields = [
            'email', 
            'first_name',
            'last_name',
            'imagenes',
            'password', 
        ]
        

    def __init__(self, *args, **kwargs):
        super(PerfilForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-group'
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            'email',
            'first_name',
            'last_name', 
            'imagenes',
            HTML("""
                {% if form.instance.imagenes %}
                <label for="id_resumen" class=" requiredField">
                Imagen asociada<span class="asteriskField">*</span> </label>
                    <div>
                        <img style="max-width: 500px;" class=" rounded mx-auto d-block img-thumbnail" src="{{ form.instance.imagenes.url }}">
                         
                    </div>
                    <br/>
                {% endif %}
                  
              
            """),
            
        )

apps/usuarios/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.generic import CreateView
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from apps.usuarios.models import Usuario
from .forms import PerfilForm, RegistroForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from ..noticias.models import Noticia , Comentario
# LOGIN


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home:inicio')
        else:
            messages.error(request, 'Usuario o contraseña invalidos')

    return render(request, 'usuarios/login.html')

# Cerrar sesion


def user_logout(request):
    logout(request)
    return redirect('usuarios:login')

# Crear cuenta


class Registro(CreateView):
    form_class = RegistroForm
    success_url = reverse_lazy('usuarios:login')
    template_name = 'usuarios/registro.html'


@login_required
def Perfil(request, pk):
    user = get_object_or_404(Usuario, pk=pk)
    if user != request.user:
        return HttpResponseForbidden("No tienes permiso para editar este perfil.")



    
    
    n = Noticia.objects.filter(autor=user).all().order_by('-fecha_publicacion')[:5]
    c = Comentario.objects.filter(usuario=user).all().order_by('-fecha_creacion')[:5]
    if request.method == 'POST':
        form = PerfilForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            
            form.save()
            return redirect('noticias:listar')
    else:
        form = PerfilForm(instance=user)

    context = {
        'form': form,
        'user': request.user,
        'posteos':n,
        'comentarios':c,
    }
    return render(request, 'usuarios/perfil.html', context)

templates/usuarios/login.html
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"
/>
{% extends 'base.html' %}
{% load static %} 
{% block contenido %}  
<link rel="stylesheet" href="{% static 'css/login.css'%}" />
{% include "navbar.html" %}
<section id="bg-blog-detail-img"  class="bg-blog-detail-img" style="background-image: url({%static '/img/login.jpg)'%}">
  <div class="overlay">
    <div class="container">
      <div id="page_content" class="formulario-registro">
        <div class="Carta_logueo">
          <form method="post">
            {% csrf_token %}
            <h1>Mi Mundo Viajando</h1>
            <h2>Iniciar Sesion</h2>
            <div>
              {% if messages %} {% for message in messages %}
              <div class="alert alert-danger">{{message}}</div>
              {% endfor %} {% endif %}
              <div class="form-item"></div>
              <input
                type="text"
                class="form-element"
                name="username"
                placeholder="Usuario"
              />
              <i class="bi bi-person-circle"></i>
            </div>
            <div class="form-item">
              <input
                type="password"
                class="form-element"
                name="password"
                placeholder="Contraseña"
              />
              <i class="bi bi-key-fill"></i>
            </div>
            <div class="form-checkbox-item">
              <input type="checkbox" id="recuerdame" checked />
              <label for="recuerdame">Recordarme</label>
            </div>
            <div class="flex">
              <button type="submit">Ingresar</button>
            </div>
            <div>
              <div class="column">
                <p>
                  ¿No tienes una cuenta?,<a href="{% url 'usuarios:registro' %}"
                    >Crea una ahora</a
                  >
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock contenido %}

templates/usuarios/perfil.html
{% extends 'base.html' %} 
{% load static %} 
{% block contenido %} 
{% include "navbar.html" %}
 {% load crispy_forms_tags %}
<div id="page_content">
  <section
    id="bg-blog-detail-img"
    style="background-image: url({{ form.instance.imagenes.url }});"
    class="bg-blog-detail-img"
  >
    <div class="overlay"></div>
  </section>
  <section id="search">
    <div class="container">
      <div class="row pt-lg-5">
        <div class="col-sm-12 col-ms-8 col-lg-8">
          <h2>Editar Perfil</h2>
          <hr />
          <form
            action=""
            class="post-form"
            method="post"
            enctype="multipart/form-data"
          >
            {% csrf_token %} {{ form.media }} {% crispy form %}
            <button class="btn btn-success boton-flotante" type="submit">
              Guardar cambios
              <i class="las la-save"></i>
            </button>
          </form>
        </div>

        <div class="col-12 col-lg-4 order-2 order-md-1 margin_small">
          {% if user.is_staff %}
          <section id="tags"   >
            <div class="container  ">
              <div class="row">
                <div class="col-12 pr-0 pl-0">
                  <div class="outer_tag mt-4 ">
                    <h2 class="main_tag ">Ultimos Posteos</h2>
                    <div class="inner-box1 panelPerfil">
                    {% for noticia in posteos %}
                    <div class="outer mt-4 display">
                      <div class="imagen-container">
                        <a href="{% url 'noticias:detalle' noticia.pk %}"
                          ><img
                            class="imagen-container-img"
                            src="{{noticia.imagenes.url}}"
                            alt="{{noticia.titulo}}"
                        /></a>
                      </div>
                      <div class="text_post minimal-post">
                        <a
                          href="{% url 'noticias:detalle' noticia.pk %}"
                          class="main"
                          title="{{noticia.titulo}}"
                          >{{noticia.titulo | slice:22 }}</a
                        >
                        <p class="date">{{noticia.fecha_publicacion}}</p>
                        <span>{{noticia.autor}}</span>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {% endif %}

          <section id="archieve" >
            <div class="container ">
              <div class="row">
                <div class="col-12 pr-0 pl-0">
                  <div class="topic_outerbox mt-4">
                    <h2>Ultimos Comentarios</h2>
                    <div class="inner-box1 panelPerfil">
                      <ul style="text-align: left;">
                        {% for comment in comentarios %}
                        <li >
                          <div  >
                          <a class="main heading ml-3 truncate " style="font-size: 13px;"
                            href="{% url 'noticias:detalle' comment.noticia.pk %}#comentario-{{comment.pk}}"
                            >
                            {{comment.noticia}}
                            
                            </a
                          </div> 
                          <p class="sub-heading " id="sub-heading-{{comment.pk}}">
                            {{comment.contenido}}
                            <br/>
                            {{comment.fecha_creacion}}
                          </p>
                        </li>
                        <hr/>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </section>
</div>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor-init.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"
></script>

{% endblock contenido %}

templates/usuarios/registro.html
{% extends 'base.html' %} 
{% load static %}
{% block contenido %}
<link rel="stylesheet" href="{% static 'css/registro.css'%}" />

{% include "navbar.html" %}
<section
id="bg-blog-detail-img" 
class="bg-blog-detail-img"
style="background-image: url({%static '/img/login.jpg)'%};">

<div class="overlay">
    <div class="container">
  <div id="page_content" class="formulario-registro">
    <h1>Crea tu Cuenta</h1>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} 
      {{ form }} 
      {% if messages %} {% for message in messages%}
      <div class="alert alert-danger">{{ message }}</div>
      {% endfor %} 
      {% endif %}
      <div class="flex">
        <button type="submit">Crear Cuenta</button>
      </div>
    </form>
    <div>
      <div class="column">
        <p>
          ¿Ya tienes una cuenta?
          <a href="{% url 'usuarios:login' %}">Ingresa</a>
        </p>
      </div>
    </div>
  </div>
</div>
</div>
  </div>
</section>
{% endblock contenido %}