apps/acercade/urls.py
from django.urls import path
from . import views

app_name = 'acercade'

urlpatterns = [
    path('', views.formulario_contacto, name='acercade'),
    path('exito/', views.exito, name='exito'),
    path('mensajes/', views.mensajes, name='mensajes'),
]

apps/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.UltimasNoticias, name='inicio')
]

apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'), 
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditarNoticia, name='edit_noticia'),
    path('detalle/ajax/cargar_comentarios/<int:noticia_id>/', views.cargar_comentarios, name='cargar_comentarios'),
    path('detalle/ajax/eliminar_comentarios/<int:id_comentario>/', views.eliminar_comentarios, name='eliminar_comentarios'),
    #path('ajax/<int:pk>', views.cargar_comentarios, name='ejemploajax'),
    #path('panel_noticias', views.PanelNoticias, name='panel_noticias'),
]

apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registro/', views.Registro.as_view(), name='registro'),
    path('perfil/<int:pk>/edit/', views.Perfil, name='perfil'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls'),name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('acercade/', include('apps.acercade.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
    #parametro 3: el nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from ..noticias.models import Noticia

# Create your views here.
def UltimasNoticias(request):
    contexto = {}
    n = Noticia.objects. all().order_by('-fecha_publicacion')[:9]
    contexto['noticias'] = n
    
    return render (request, 'home.html', contexto)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="author" content="Informatorio Chaco" />
    <!-- description -->
    <meta
      name="description"
      content="Blog para trabaja practico final de Informatorio Chaco."
    />
    <!-- keywords -->
    <meta
      name="keywords"
      content="chaco, viajar, clean, informatorio,, html5, css3, djnago, blog,"
    />
    <!-- Page Title -->
    <title>Blog | Mi mundo viajando</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/favicon.ico'%}" />
    <!-- Bundle -->
    <link rel="stylesheet" href="{% static 'vendor/css/bundle.min.css'%}" />
    <!-- Plugin Css -->
    <link rel="stylesheet" href="{% static 'vendor/css/cubeportfolio.min.css'%}" />
    <script src="{% static 'vendor/js/popper.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css'%}" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/line-awesome.min.css'%}" />
    <!-- Style Sheet -->
    <link rel="stylesheet" href="{% static 'vendor/css/owl.carousel.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <link rel="stylesheet" href="{% static 'css/guille.css'%}" />
    <link rel="stylesheet" href="{% static 'vendor/css/jquery.toast.min.css'%}" />
 
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/guille.js'%}"></script>
  
  </head>

  <body data-spy="scroll" data-target=".navbar" data-offset="150">
    <!--  PRELOADER  -->
    <div class="loader-area">
      <div class="loader">
        <div class="one"></div>
        <div class="two"></div>
        <div class="three"></div>
      </div>
    </div>

    {% block contenido %}

    {% endblock contenido %}
    {% include "footer.html" %}
    <!-- JavaScript -->
    <script src="{% static 'vendor/js/bundle.min.js'%}"></script>

    <!-- Plugin Js -->
    <script src="{% static 'vendor/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'vendor/js/jquery.cubeportfolio.min.js'%}"></script>
  
    <!-- custom script -->
    
 
    <script src="{% static 'js/jquery.fancybox.js'%}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js'%}"></script>
    <script src="{% static 'js/mediaelement-and-player.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'vendor/js/parallaxie.min.js'%}"></script>
    <script src="{% static 'vendor/js/jquery.toast.min.js'%}"></script>
  
    <script src="{% static 'js/script.js'%}"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<section id="footer" class="footer ">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <ul class="footer_ul">
          <a
            style="text-decoration-line: none"
            href="https://www.facebook.com/agenciamimundoviajero"
            target="_blank"
          >
            <li class="footer_list">
              <i class="lab la-facebook-f"></i>
            </li>
          </a>

          <a
            style="text-decoration-line: none"
            href="https://www.instagram.com/mi.mundo.viajando/"
            target="_blank"
          >
            <li class="footer_list"><i class="lab la-instagram"></i></li>
          </a>
          <a
            style="text-decoration-line: none"
            href="https://twitter.com/MiMundoViajando"
            target="_blank"
          >
            <li class="footer_list"><i class="lab la-twitter"></i></li>
          </a>
          <a
            style="text-decoration-line: none"
            href="mailto:mimundoviajndo@correo.com"
          >
            <li class="footer_list"><i class="las la-envelope"></i></li>
          </a>
        </ul>
        <p class="info footer_text">
          <i class="far fa-copyright"></i>2023 Mi Mundo Viajando. Hecho con amor
          por viajeros
        </p>
      </div>
    </div>
  </div>
</section>

templates/home.html
{% extends 'base.html' %} {% load static %} {% block contenido %}

<header>
  <nav
    id="my-nav"
    class="navbar navbar-expand-lg navbar-light rounded-bar sidemenu-nav"
  >
    <div class="logo width-logo1">
      <a href="/"
        ><img src="{% static 'img/logo-white.png'%}" alt="Logo Img"
      /></a>
    </div>
    <a   class="sidemenu_btn menu-btn-home" id="sidemenu_toggle">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </nav>

  {% include "menu.html" %}
</header>

<section id="banner-img" class="banner-img bg-banner-img">
  <div class="row no-gutters">
    <div class="col-12 col-md-5"></div>
    <div class="col-12 col-md-7">
      <div class="overlay"></div>
      <div class="row no-gutters height1">
        <div
          class="col-2 d-flex justify-content-center align-items-center"
        ></div>
        <div class="col-10 d-flex align-items-center">
          <h1 class="main-heading text-white">MI<br />MUNDO<br />VIAJANDO</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="areacontenido">
<section id="about" class="about">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6">
        <div class="about-text text-left d-flex">
          <p class="verticle-text text-grey pt-2">Inspirador</p>
          <h1 class="main-heading ml-3">
            NAVEGANDO POR EXPERIENCIAS INOLVIDABLES
          </h1>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <p class="sub-heading text-grey">
          <br />
          En Mi Mundo Viajando, te sumergirás en relatos llenos de color y
          emoción, descubriendo secretos locales, joyas ocultas y consejos
          expertos para maximizar tu experiencia viajera. Desde playas
          paradisíacas hasta ciudades vibrantes, nuestro objetivo es inspirarte
          a crear recuerdos extraordinarios mientras exploras los rincones más
          asombrosos del planeta. ¡Embárcate en esta travesía con nosotros y haz
          de cada viaje una obra maestra de aventuras y descubrimientos!
        </p>
      </div>
    </div>
  </div>
</section>

<section id="portfolio" class="portfolio">
  <div class="container">
    <div id="js-grid-masonry-projects" class="cbp cbp-l-grid-masonry-projects">
      {% for noticia in noticias %}
      <div class="cbp-item">
        <div class="cbp-caption">
          <div class="cbp-caption-defaultWrap">
            <img src="{{noticia.imagenes.url}}" alt="" />
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <a
                  href="{% url 'noticias:detalle' noticia.pk %}"
                  class="btn blog-btn cbp-l-caption-buttonLeft"
                  >Leer Más</a
                >
              </div>
            </div>
          </div>
        </div>
        <div class="portfolio-text">
         
          <a class="text-black" href="{% url 'noticias:detalle' noticia.pk %}"
            ><h2 class="heading ml-3 texto-con-tres-lineas">{{noticia.titulo}}</h2></a
          >
          <p class="date text-grey">{{noticia.fecha_publicacion}}</p>

          <div class="horizontal-line"></div>
          <p class="sub-heading text-grey mt-3 truncate">{{noticia.resumen}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section id="testimonial" class="testimonial">
  <div class="row bg-black">
    <div class="col-12 col-md-6 p-0">
      <img src="{% static 'img/testimonial-img.jpg'%}" alt="image" />
    </div>
    <div
      class="col-12 col-md-6 pl-4 pl-md-0 d-flex justify-content-center align-items-center"
    >
      <div class="owl-testimonial owl-carousel owl-theme">
        <div class="item">
          <p class="heading-large text-white">
            "MiMundoViajando convierte cada viaje en una aventura inolvidable.
            Sus relatos auténticos y consejos prácticos han transformado mis
            experiencias, haciéndolas más emocionantes y llenas de
            descubrimientos."
          </p>
          <div class="rating">
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
          </div>
        </div>
        <div class="item">
          <p class="heading-large text-white">
            "Inspiración constante y guía infalible: Mi Mundo Viajando ha elevado
            mis viajes a nuevas alturas. Cada artículo es una ventana a destinos
            asombrosos, proporcionando insights valiosos para explorar el mundo
            de manera auténtica."
          </p>
          <div class="rating">
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
          </div>
        </div>
        <div class="item">
          <p class="heading-large text-white">
            "Mi Mundo Viajando no solo es un blog; es una comunidad apasionada.
            Conectándome con otros amantes de los viajes, he creado recuerdos
            inolvidables gracias a las recomendaciones compartidas. Este blog es
            mi compañero inseparable en cada travesía."
          </p>
          <div class="rating">
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
            <i class="las la-star rating-star"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


</div>
{% endblock contenido %}

templates/menu.html
{% load static %}
<div class="outer-wrapper">
    <div class="overlay1">
      <a class="close-outerwindow"><i class="las la-times"></i></a>

      <nav class="navbar-1 w-100">
        <div class="row text-center">
          <div class="col-12">
            <div class="logo-img text-center">
              <a href="index-blog.html"
                ><img src="{% static 'img/logo.png'%}" alt="Logo Img"
              /></a>
            </div>

            <ul class="navbar-nav mt-5 text-center small-nav">
              <li class="nav-item">
                <a class="nav-link active" href="/">Home</a>
                
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'noticias:listar' %}">Blogs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'acercade:acercade' %}">Acerca de</a> 
              </li>
              <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" style="font-size: 25px;color: #d3a80b;" href="{% url 'usuarios:logout' %}">Cerrar sesion</a>
              {% else %}
              <a class="nav-link" style="font-size: 25px;color: #d3a80b;" href="{% url 'usuarios:login' %}">Iniciar sesion</a>
              {% endif %}
              </li>
            </ul>
            <ul class="footer_ul text-center mt-3 margin-top">
              <li class="footer_list"><i class="lab la-facebook-f"></i></li>
              <li class="footer_list"><i class="lab la-twitter"></i></li>
              <li class="footer_list"><i class="lab la-google-plus"></i></li>
              <li class="footer_list"><i class="lab la-linkedin-in"></i></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>

templates/navbar.html
{% load static %} 
<header>

    <nav id="my-nav" class="navbar navbar-expand-lg navbar-light rounded-bar fixed-navbar">
        <div class="row w-100 m-0">
            <div class="col-3 p-0 mt-3 mt-md-4">
                <ul class="navbar-icons">
                    <li onclick="goBack()" class="navbar_list">
                        <i class="las la-undo"></i>
                    </li>
                    
                    {% if user.is_authenticated %}
                    <li class="navbar_list2 nav-item dropdown">
                          <a  class="nav-link dropdown-toggle texto-a-mostrar" href="#" style="color: #2b2b2b;text-decoration: none;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="las la-user"></i>
                               
                          </a>
                          <a  class="nav-link dropdown-toggle texto-a-ocultar" href="#" style="color: #2b2b2b;text-decoration: none;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="las la-user"></i>
                             {{user}} 
                          </a>
                         
                          <div style="margin-left: 70px;top: 80%;z-index=99999" class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'usuarios:perfil' pk=user.pk %}" style="text-decoration: none;" href="#">Mi Perfil</a>
                            {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'acercade:mensajes' %}" style="text-decoration: none;" href="#">Mensajes</a>
                                                      
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a style="text-decoration: none;" class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar sesion</a>
                          </div>
                    </li>
                    {% endif %}
                     
                </ul>
                 
            </div>
            
            <div class="col-6">
                <div class="logo ml-auto mr-auto width-logo text-center mt-2 mt-md-3">
                    <a href="/"><img src="{% static 'img/logo.png'%}" alt="Logo Img"></a>
                    
                </div>
            </div>

            <div class="col-3 p-0 text-right">
                
                <div class="  mt-3 mt-md-4">
                    <a   class="sidemenu_btn menu-btn " id="sidemenu_toggle">
                        <span></span>
                        <span></span>
                        <span></span>
                      </a>
                </div>
            </div>
        </div>

    </nav>
    {% include "menu.html" %}
</header>

templates/nosotros.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Nosotros{% endblock titulo %}
{% block contenido %}
    <h2>soy de la comision 6</h2>
{% endblock contenido %}